apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-helmvalues
  namespace: argocd-e2e
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd-e2e
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      targetRevision: "18.2.3"
      chart: nginx
      helm:
        valueFiles:
          - $values/kustomize-helmvalues/source2/values-0.yaml
          - $values/kustomize-helmvalues/source2/values.yaml
    - repoURL: https://github.com/chengfang/image-updater-examples.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/chengfang/image-updater-examples.git
      targetRevision: main
      path: kustomization-write-target/source
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
